version: '3.7'
services:
  postgres-go:
    container_name: postgres-go
    build: 
      context: .
      dockerfile: dockerfile.postgres
    ports:
      - 5433:5432
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app-go:
    container_name: app-go
    build: 
      context: .
      dockerfile: dockerfile.app
    ports:
      - 3000:3000
    depends_on:
      postgres-go:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
    name: backend